version: '2'
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset
    volumes:
      - mysql:/var/lib/mysql
  web:
    build: .
    image: amancevice/superset
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    ports:
      - "8088"
    volumes:
      - "./superset_config.py:/home/superset/superset_config.py"
volumes:
  mysql:
    external: false
  redis:
    external: false
